### ISSUE TITLE
Get the Federalist branch preview URL as a comment our GitHub PR

### ISSUE THREAD

**Issue by jeremyzilar** [cloud-gov/pages-core#2350]
#### User Story

As a user, I would like to be able to get the Federalist, branch preview URL immediately after submitting a pull request, and not have to wait for the site to build. 
I need this URL available in the PR for others on my team to be able to preview the changes we are making.

The current way of getting at the preview URL is not intuitive for people we work with who need to be able to verify and approve changes. These are people who are largely new to GitHub, or not in it every day. _(it would also be easier for the experts too)_

### What we are doing now

Our process now is to:
1. Create the PR
2. wait for the build to finish (~7mins) so we can get get the link
3. Go to the link and navigate to the specific page we edited
4. Copy the link and edit the body of the main PR and put it in as a "preview" link 
5. Send the PR link to someone to review

Having an assurance that a preview link will appear in the comments (from Federalist) after the  build completes would mean that more people on our team can find the preview link.

[Here is the discussion thread in Slack »](https://gsa-tts.slack.com/archives/C1NUUGTT5/p1565265002049800)

Would it be possible to make a script in Federalist (or maybe through CircleCI) that adds the branch Preview URL as a comment in the PR on GitHub?

**Comment by eddietejeda** [comment]
@amirbey, we've talked about caching builds for this reason. This is a situation where the caching would certainly make this a non-issue, since most of the time the build will complete in seconds.

**Comment by jeremyzilar** [comment]
This is still a big need for us. We work with a lot of people around TTS that are not too familiar with GitHub or Federalist and finding the preview link at the bottom of a PR is consistently a challenge.

I can explore using CircleCi as a means to create the preview URL: https://github.com/GSA/digitalgov.gov/issues/1529

But would first like to know if this is better done on the Federalist side of things

**Comment by afeld** [comment]
There are a few things going on here:

- The build times
- Knowing when a build completes if you aren't staring at the pull request / logs
- Visibility of the preview URLs

For the latter, I wonder if using [deployments](https://developer.github.com/v3/guides/delivering-deployments/) rather than [status checks](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-status-checks) would be help. Could have sworn I saw a screenshot of (forthcoming?) UI from GitHub that shows deployment preview URLs in the pull request, but can't find it.

**Comment by apburnes** [comment]
N/A
