### ISSUE TITLE
rename Federalist to Pages in Slack

### ISSUE THREAD

**Issue by amirbey** [cloud-gov/pages-core#3613]
#### User Story

<TODO>

#### Background (Optional)

<TODO>

#### Acceptance Criteria

- [x] :pages: slack emoji is available for use
- [x]  slack channels are renamed pages

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [ ]  create :pages slack emoji
- [ ]  rename slack channels???

**Comment by drewbo** [comment]
Because there are a number of adjacent potential issues with this change, I'd like to write up a proposal here before we do any renaming:
- "Pages" by itself doesn't really give enough context to external users so I'll propose we use "cloud.gov Pages" in public settings where possible (even if it's a little bit of a mouthful). For Slack purposes do people prefer `cloud-gov-` as a prefix (more explicit but longer and doesn't match existing channels) or `cg-`?
- We should update all the channels listed in our [primary info doc](https://docs.google.com/document/d/17vcjJ0PB4yxCUIDoKh8TP3mYK5ArhF90SymGrITxEx0/edit) in addition to our logging based channels.
- The aforementioned document also needs some updating and is linked in the main Slack channel. Let's throw so time on the calendar for an internal discussion of how to keep this up-to-date.
- Finally we should seek out all places where the Slack channels are mentioned/used as I'm not sure whether Slack will automatically redirect ([they do for workspaces](https://slack.com/help/articles/201663443-Change-your-workspace-or-org-name-and-URL)) or for how long. Brief initial list:
  - CI pipelines use a CredHub variable `((slack-channel))` for sending status alerts
  - TTS or cloud.gov documentation (e.g. https://handbook.tts.gsa.gov/tools/federalist/)
  - Presentations?
