### ISSUE TITLE
Update production domain services to point CDN origin to the pages proxy

### ISSUE THREAD

**Issue by apburnes** [cloud-gov/pages-core#4015]
As we transition from federalist to pages, we need to update our production domain services to point their CDN origin from the federalist proxy to the pages proxy. In support of completing https://github.com/cloud-gov/product/issues/2092.

## Acceptance Criteria

- [ ] Query our current production domains from the database to get the current origin ie `<site-bucket-guid>.app.cloud.gov`
- [ ] Create a script to query our production CDN services in our cf org `sites` space, run `cf update-service` to point the CDN service's origin to point to the pages proxy at `<site-bucket-guid>.sites.pages.cloud.gov`.

**Comment by svenaas** [comment]
Working in cloud-gov/pages-core#4029 — and cloud-gov/cg-scripts#238 and cloud-gov/cg-scripts#238 — and back in cloud-gov/pages-core#4029 I produced a couple of scripts that tackle this in various ways. Turns out they only do the trick for external domains, so @apburnes went and tackled the cdn-routes a different way, which I'm hoping he'll document so that I can learn how to do it. 

As of this writing I have finished updating the origins for all the provisioned `-ext` domains in Pages, and between Andrew and me we're at
```
> select count(*) from domain where state='provisioned' and origin like '%app.cloud.gov';
 count 
-------
     0
```

Andrew, can you think of more we need to do on this part of the work, or can we close this?

**Comment by apburnes** [comment]
👍 I think we can close this one out.
