### ISSUE TITLE
Move the site deletion process into a queued job

### ISSUE THREAD

**Issue by apburnes** [cloud-gov/pages-core#4047]
When a user is deleting a site, the UI should be responsive and the delete action should be successful. Currently, the delete action happens during the request to the API, so the user will experience a long loading screen while the site deletes and if request gets interrupted, the sites infrastructure may not be properly deleted.

## Acceptance Criteria

- [x] Update the API endpoint to soft delete the site's record in the database and kick off the job to delete its infrastructure
- [x] Update the [`./api/services/SiteDestroyer` service](https://github.com/cloud-gov/pages-core/blob/staging/api/services/SiteDestroyer.js) to be able to be run as background job
- [x] Add the job to the [`api/workers` directory](https://github.com/cloud-gov/pages-core/tree/staging/api/workers)

**Comment by drewbo** [comment]
Started looking into this and came across a few questions/clarifications:
- I'm planning to leave `SiteDestroyer.destroySite` as a non-background job since it can surface the "domain still exists" error + the DB deletion (and potentially the webhook deletion) before proceeding to `SiteDestroyer.destroySiteInfra` (which should become a background task)
- Right now it looks like we call both the `Mailer` and `Slacker` from within `destroySiteInfra` to alert on error. Two questions here:
  - Will we still have access to these in the background workers? (since they also need to establish queue connections)
  - Does the Slacker function work here? I remember seeing delete failure emails but nothing in slack. It's also sending them to `federalist-supportstream` which could be the cause of the error.

Otherwise I should have this going early next week

**Comment by apburnes** [comment]
The plan makes sense to me. 

For the workers, all of the codebase is available to them since they share the same env, dependencies, and runtime. They're just deployed as a separate worker process by CloudFoundry so we will be able to send the error alerts in the background job. As for the `Slacker` alert, I can only find test alerts in the channel history and it may need some further investigation.
