### ISSUE TITLE
Investigate Archive Build Log Job

### ISSUE THREAD

**Issue by apburnes** [cloud-gov/pages-core#4069]
Investigate the build log job archiver to make sure it is properly moving logs from the db into s3 and is cleaning up old log data in the database.

## Note

There are old logs in the db that need to be verified they were archived and then deleted.

**Comment by drewbo** [comment]
The only old day remaining in the DB is May 18th, 2022. My instinct is to remove those old DB logs now for a few reasons:
- They are beyond the retention period in S3
- Our queue monitoring doesn't extend far enough to capture a failure there: [bull board ui](https://queues.pages.cloud.gov/queues/queue/archive-build-logs)
- Our kibana logs don't extend far enough to capture a failure there: [kibana logs link](https://logs.fr.cloud.gov/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-1y,to:now))&_a=(columns:!('@message'),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'logs-app*',key:'@cf.app',negate:!f,params:(query:pages-production),type:phrase),query:(match_phrase:('@cf.app':pages-production)))),index:'logs-app*',interval:auto,query:(language:kuery,query:'%22Archive%20build%20logs%22'),sort:!()))
- The [archive function itself](https://github.com/cloud-gov/pages-core/blob/main/api/workers/jobProcessors/archiveBuildLogsDaily.js#L20-L58) seems (1) reasonable and (2) to be otherwise working based on a quick scan of the logs in the DB and the ability to query logs older than one day stored on S3.

My only hardening idea is that we could update the archiving function to pull logs from the previous 3 or 7 (or whatever) days but still run daily. This would mostly operate the same but in the case where the daily function fails for whatever reason, we could potentially pick up the remaining logs on the next day. There is a slight chance to timeout the worker if there were too many logs. Thoughts?

**Comment by apburnes** [comment]
That makes sense to me. With the expanded date rage, let's make sure we aren't replicating any logs in S3 and we're properly deleting the build logs in the DB.

Also, do we have active alerting to email or Slack when an archive job fails?

**Comment by drewbo** [comment]
The date logic is to select the logs from the DB so if they aren't already deleted, they shouldn't be archived yet and this would avoid duplication (although it's possible that it errors [in between](https://github.com/cloud-gov/pages-core/blob/main/api/services/build-logs/build-logs.js#L48-L50) but because we're using `putObject` I don't think it will duplicate).

The error is only logged but we could add the Mailer/Slacker logic here that is present in site deletions

**Comment by apburnes** [comment]
Sounds good. Let's add the Mailer/Slacker notices for some additional observability on failures.
