### ISSUE TITLE
Templatize and start the Pages users roles and orgs check with Zendesk roles and orgs

### ISSUE THREAD

**Issue by apburnes** [cloud-gov/pages-core#4246]
Create an issue template to setup a recurring task to check Pages users roles and orgs with their Zendesk ones.

## To Do
- [x] Draft issue template to make this a recurring monthly issue
- [x] #4258 
- [x] Create a new issue based on the template as this month's user roles/orgs check
- [x] https://github.com/cloud-gov/product/issues/2744
- [x] Flesh out issue template for subsequent months

**Comment by svenaas** [comment]
Blocked until the next `pages-core` release makes the reports available in production. Then we'll make an issue from [the new template](https://github.com/cloud-gov/product/blob/main/.github/ISSUE_TEMPLATE/pages-3-zendesk-sync.md) and this month's sync can move forward.

**Comment by svenaas** [comment]
First monthly sync: https://github.com/cloud-gov/product/issues/2744

**Comment by svenaas** [comment]
@Ephraim-G, when you close out https://github.com/cloud-gov/product/issues/2744 it might check off the corresponding task here; otherwise you can check that off too. Then the final task here is to update the [issue template](https://github.com/orgs/cloud-gov/projects/27/views/3?pane=issue&itemId=37761823) if any update is needed. Perhaps a note documenting the need to exclude users who are unimportable because they lack email addresses? I also think it would be good for you to provide specific steps on how you prepare the Name column before import, so that if one of us does that task in a future month we can do it consistently.

**Comment by Ephraim-G** [comment]
@svenaas Yes I plan on adding some more steps in regards to cleaning/organizing the users.csv for import and will add that note about excluding certain users.

**Comment by Ephraim-G** [comment]
@svenaas done ✅  pending review https://github.com/cloud-gov/product/pull/2751
