### ISSUE TITLE
Bucket deletion should remove all keys/prefixes recursively

### ISSUE THREAD

**Issue by drewbo** [cloud-gov/pages-core#4270]
Right now the site deletion script is careful to only remove certain prefixes from S3 buckets. This is done for legacy reasons when all sites where in the same bucket. Now it creates issues when we add new prefixes to the bucket root (e.g. `_cache`, `_tasks`) and are unable to delete sites.

Let's rewrite the S3 bucket deletion script to recursively remove all items.

## Acceptance Criteria

- [x] Site deletion removes associated S3 bucket regardless of contents

**Comment by apburnes** [comment]
Adding to blocked until https://github.com/cloud-gov/pages-core/issues/3989 is complete

**Comment by apburnes** [comment]
Closed by #3989

**Comment by svenaas** [comment]
@drewbo was this intended to refer to `S3SiteRemover` — which, through `S3Helper`, now deletes all bucket objects instead of the bucket objects matching specific prefixes — or to the script `remove-bucket-website-configs.js` which, per its name, removes bucket website configs but for _all_ sites, which is not something I hope we'll need often? 

The latter script instantiates its own S3 client instead of using S3Helper, and it uses the older style function instead of a  command, but I believe its implementation remains valid.

**Comment by svenaas** [comment]
I'm trying to figure out whether there remains anything to do here. @apburnes moved it from Blocked to Doing, assigned it to me, noted in a comment that it was closed, but it didn't actually _get_ closed.

**Comment by svenaas** [comment]
The first part was indeed taken care of by my changes.

**Comment by drewbo** [comment]
Refers to `S3SiteRemover`; closed via #3989

**Comment by svenaas** [comment]
Thanks for confirming.
