### ISSUE TITLE
Add queue to delete site builds from database after 180 days

### ISSUE THREAD

**Issue by apburnes** [cloud-gov/pages-core#4336]
# Canceled

After identifying and discussing downsides with the deletion of site builds we decided not to merge the changes implemented for this issue, and take different actions instead.

---

# Original intent

To align our [site build log storage policy](https://cloud.gov/pages/documentation/previews/#builds-and-logs), create a queue to run a nightly job to delete builds from the database.

## Background

- Follow the same pattern as the archive build logs queue
  - [Connecting the queue worker](https://github.com/cloud-gov/pages-core/blob/main/api/workers/index.js#L85)
  - [Adding to the queues](https://github.com/cloud-gov/pages-core/blob/main/api/workers/index.js#L98) 
  - [Creating the job](https://github.com/cloud-gov/pages-core/blob/main/api/workers/jobProcessors/archiveBuildLogsDaily.js)
  - [Add to the bull board](https://github.com/cloud-gov/pages-core/blob/main/api/bull-board/app.js#L41)

- Related to https://github.com/cloud-gov/pages-core/issues/4277

## Acceptance Criteria

- [x] Create a queue to delete build logs older than 180 days nightly
- [x] Create and test a job that is run by the worker to query and delete all builds that are older than 180 nights
- [x] Add the queue to the bull board UI
- [x] Add test to verify the UI functions when a site has no builds

**Comment by svenaas** [comment]
@apburnes @drewbo Is hard deletion appropriate here, or should Build be set up for soft deletion before we start running this job?

**Comment by svenaas** [comment]
It's only in production that we archive build logs to S3, subject to expiration and removal, so we could run the new worker in production only, but it would be advantageous to let it run in the other environments both for cleanup and test purposes.

**Comment by drewbo** [comment]
- soft deletion, but I don't have a great argument for either way
- I'm up for running it in staging/dev but maybe we should also run the build log archiving there to create a consistent experience

**Comment by svenaas** [comment]
Regarding the acceptance criterion "Add test to verify the UI functions when a site has no builds": [happily, there is already such a test.](https://github.com/cloud-gov/pages-core/blob/main/test/frontend/components/site/siteBuilds.test.js#L174-L184)

That test, however, drew my attention to the fact that [when a site has no builds](https://github.com/cloud-gov/pages-core/blob/main/frontend/components/site/siteBuilds.jsx#L161-L162) our alert banner reads:
> #### This site does not yet have any builds
> If this site was just added, the first build should be available within a few minutes.

Should we revise this language? I'm concerned that the current behavior could alarm a user of a longstanding site which is live but hasn't built in the past six months and consequently has no builds. I suggest revising the alert banner header so that the banner reads:
> #### This site has not had any builds in the past 180 days
> If this site was just added, the first build should be available within a few minutes.

**Comment by apburnes** [comment]
Scheduled time for a refinement on 1/17/24.

**Comment by svenaas** [comment]
I believe this work is complete and correctly functioning, but we've decided it's not the right thing to do.
